version: "3.8"

services:
  db:
    image: postgres:15
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"   # opcional (para pgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: taskmanager-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/taskmanager
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgres_data:
